version: "3.9"
services:
  servernode:
    build: .
    ports:
      - "4000:4000"
    links:
      - mi_app
  mi_app:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INIT_ROOT_USERNAME:luis
      - MONGO_INIT_ROOT_PASSWORD:password
